[package]
name = "rustlife"
version = "0.1.0"
authors = ["Hadley Deary <tdeary@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
olc_pixel_game_engine = "0.5.0"
